import React from 'react';
import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Financial Disclaimer | Freelance Tax Calculator Suite',
  description: 'Legal disclaimer regarding estimation accuracy, tax advice, and calculation boundaries.',
  alternates: {
    canonical: 'https://www.freelancecalcsuite.online/disclaimer',
  },
};

export default function DisclaimerPage() {
  return (
    <main className="max-w-4xl mx-auto px-4 py-12 text-slate-300">
      <Link 
        href="/" 
        className="inline-flex items-center gap-2 mb-8 text-xs font-semibold text-cyan-400 no-underline hover:text-cyan-300 transition-colors"
      >
        <span>&larr;</span> Back to Calculator
      </Link>

      <div className="border-b border-white/10 pb-6 mb-8">
        <h1 className="text-3xl font-bold tracking-tight text-white sm:text-4xl">Financial & Tax Disclaimer</h1>
        <p className="mt-2 text-xs text-slate-400">Last updated: August 15, 2026</p>
      </div>

      <div className="space-y-8 text-sm leading-relaxed">
        <section className="space-y-3">
          <h2 className="text-xl font-bold text-white">1. Informational Purposes Only</h2>
          <p>
            The calculations, tax estimations, recommended hourly rates, and financial metrics provided by 
            this application (the &quot;Service&quot;) are intended solely for general informational and educational 
            purposes. None of the content or calculation outputs generated by the Service constitute formal 
            tax, accounting, legal, or financial advice.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-white">2. No Client or Professional Relationship</h2>
          <p>
            Your use of this web application does not create a Certified Public Accountant (CPA), fiduciary, 
            or other professional services relationship between you and the operators of this website.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-white">3. Estimation Accuracy & Limitations</h2>
          <p>
            While we strive to keep our tax baseline formulas and mathematical logic accurate in accordance with 
            current IRS guidelines, outputs are strictly estimates. Actual tax liabilities depend on individual 
            deductions, state and municipal tax brackets, filing statuses, and local tax regulations. You should 
            always consult with a licensed CPA or tax attorney for specific filing advice.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-white">4. Limitation of Liability</h2>
          <p>
            Under no circumstances shall the owners, operators, or developers of this website be liable for any 
            direct, indirect, incidental, or consequential damages resulting from your reliance on the 
            information provided by this Service.
          </p>
        </section>
      </div>
    </main>
  );
}