import React from 'react';
import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Financial Disclaimer | Freelance Tax Calculator Suite',
  description: 'Legal disclaimer regarding estimation accuracy, tax advice, and calculation boundaries.',
};

export default function DisclaimerPage() {
  return (
    <main className="max-w-4xl mx-auto px-4 py-12 prose dark:prose-invert">
      {/* Back Button */}
      <Link 
        href="/" 
        className="inline-flex items-center gap-2 mb-8 text-sm font-semibold text-cyan-400 no-underline hover:text-cyan-300 transition-colors"
      >
        <span>&larr;</span> Back to Calculator
      </Link>

      <h1>Financial & Tax Disclaimer</h1>
      <p className="text-sm text-gray-500">Last updated: August 1, 2026</p>

      <h2>1. Informational Purposes Only</h2>
      <p>
        The calculations, tax estimations, recommended hourly rates, and financial metrics provided by 
        this application (the &quot;Service&quot;) are intended solely for general informational and educational 
        purposes. None of the content or calculation outputs generated by the Service constitute formal 
        tax, accounting, legal, or financial advice.
      </p>

      <h2>2. No Client or Professional Relationship</h2>
      <p>
        Your use of this web application does not create a Certified Public Accountant (CPA), fiduciary, 
        or other professional services relationship between you and the operators of this website.
      </p>

      <h2>3. Estimation Accuracy & Limitations</h2>
      <p>
        While we strive to keep our tax baseline formulas and mathematical logic accurate, outputs are 
        strictly estimates. Actual tax liabilities depend on individual deductions, state tax brackets, 
        and local tax regulations. You should always consult with a licensed CPA or tax professional.
      </p>

      <h2>4. Limitation of Liability</h2>
      <p>
        Under no circumstances shall the owners, operators, or developers of this website be liable for any 
        direct, indirect, incidental, or consequential damages resulting from your reliance on the 
        information provided by this Service.
      </p>
    </main>
  );
}